http:
  port: "8081"

apiId: ""

dataBase:
  DE:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  AR:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  AU:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  BR:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  CL:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  CO:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  CR:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  EC:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  SV:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  ES:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  PH:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  FR:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  GT:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  HN:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  IN:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  MX:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  NI:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  PY:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  PE:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  PT:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  UY:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
