http:
  port: "8081"
 
apiId: ""
 
dataBase:
  DE:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  AR:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  AU:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  BR:
    host: "SALDOSPREMHBDPRE.emea.prosegur.local"
    port: "1521"
    user: "br00127510"
    password: "MH7A4MQ7"
    serviceName: "SALDOSPREMH"
    schema: "iac003em"
  CL:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  CO:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  CR:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  EC:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  SV:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  ES:
    host: "SALDOSPREMHBDPRE.emea.prosegur.local"
    port: "1521"
    user: "br00127510"
    password: "MH7A4MQ7"
    serviceName: "SALDOSPREMH"
    schema: "iac001em"
  PH:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  FR:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  GT:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  HN:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  IN:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  MX:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  NI:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  PY:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  PE:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
  PT:
    host: "SALDOSPREMHBDPRE.emea.prosegur.local"
    port: "1521"
    user: "br00127510"
    password: "MH7A4MQ7"
    serviceName: "SALDOSPREMH"
    schema: "iac002em"
  UY:
    host: ""
    port: ""
    user: ""
    password: ""
    serviceName: ""
    schema: ""
